### ISSUE TITLE
Todo list for oreo-pie

### ISSUE THREAD

**Issue by 488315** [mt8163/android_device_amazon_karnak#2]
* [x] fix codecs in pie
* [x] increase the sound quality in pie 
* [x] fix headphone routing
* [x]  Fix Bluetooth and wifi driver crashing
* [x] implement early mount
* [x] fix battery issues
* [x] make custom kernel to work
* [x] fix egl issues if there is one 
* [x] test vendor symlink

**Comment by DrRayThe2nd** [comment]
I've been using your LineageOS 14 build for some time now and have been enjoying it. Keep up the good work!

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by 488315** [comment]
Thanks! I'm still working on improvement on pie

**Comment by ShayBox** [comment]
Has the wifi bug been fixed from 14

**Comment by DrRayThe2nd** [comment]
> Has the wifi bug been fixed from 14

@ShayBox I use 14 regularly and have had no problems with the Wi-Fi.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by ShayBox** [comment]
@DrRayThe2nd mine is constantly disconnecting from wifi randomly and not reconnecting, it will say connecting until it fails then the network disappears and eventually reappears and connects, the network itself is fine, could be something with it switching between 2.4 and 5ghz, I don't know if this tablet even supports 5ghz but my router doesn't split them into separate ssids like some do, that's my best guess, but stock works fine.

**Comment by DrRayThe2nd** [comment]
@ShayBox I've used both 2.4GHz and 5GHz networks and both work fine for me, however I haven't tried a dual band network (like it sounds like you have) so maybe that's the issue.

**Comment by ShayBox** [comment]
That is what I have, though I didn't know the word for it, I'll see if I can split them and see if that fixes it and report back

**Comment by ShayBox** [comment]
It seems restarting fixes it for a day or so, but it gets bad, maybe it's just something I did to my install, but I'm excited to see lineage 17 being worked on :+1:

**Comment by 488315** [comment]
> It seems restarting fixes it for a day or so, but it gets bad, maybe it's just something I did to my install, but I'm excited to see lineage 17 being worked on

Lineage 17 wont boot because of the new graphics interface that is different than pie

**Comment by 488315** [comment]
All fixed 👍
